content_file: 'C:/Sample Data/Job_Ad_QA_data/content_cleaned.json'
saved_models_path: 'C:/Sample Data/Job_Ad_QA_data/saved_models'
LLM_pretrained_path: 'C:/Sample Data/Job_Ad_QA_data/saved_models/llm_saved_model'
model_output_path: 'C:/Users/Vikram Pande/Side_Projects/Model_Output'
training_log_path: 'C:/Users/Vikram Pande/Side_Projects/Training_Logs'
pretrained_model: 'gpt2'
batch_size: 100