model_ver: 0.01
content_path: 'C:/Sample Data/Job_Ad_QA_data'
content_file: 'C:/Sample Data/Job_Ad_QA_data/content_cleaned.txt'
LLM_pretrained_path: 'C:/Sample Data/Job_Ad_QA_data/saved_models/llm_saved_models'
model_output_path: 'C:/Users/Vikram Pande/Side_Projects/Model_Output'
training_log_path: 'C:/Users/Vikram Pande/Side_Projects/Training_Logs'
pretrained_HG_model: 'gpt2'
learning_rate: 1e-08