model_ver: 'v0.0.1'
start_id: 0704.0001
end_id: 0704.0500
files_path: 'C:/Sample Data/OCR_arxiv_data'
extracted_PNG_path: 'C:/Sample Data/OCR_arxiv_data/Extracted_PNGs'
OCR_Results_path: 'C:/Sample Data/OCR_arxiv_data/OCR_Results'
preprocessed_image_width: 224 #224
preprocessed_image_height: 224 #224
scale_x: 1.2
scale_y: 1.2