model_ver: 'v0.0.1'
start_id: 0704.0001
end_id: 0704.0500
files_path: 'C:/Sample Data/OCR_arxiv_data'
extracted_text_path: 'C:/Sample Data/OCR_arxiv_data/Extracted_text'
extracted_images_path: 'C:/Sample Data/OCR_arxiv_data/Extracted_images'
preprocessed_images_path: 'C:/Sample Data/OCR_arxiv_data/Preprocessed_images'
preprocessed_image_width: 224 #800
preprocessed_image_height: 224 #600