model_ver: 0.02
content_path: 'C:/Sample Data/Job_Ad_QA_data'
content_file: 'C:/Sample Data/Job_Ad_QA_data/content_cleaned.txt'
train_file: 'C:/Sample Data/Job_Ad_QA_data/train_set.txt'
validate_file: 'C:/Sample Data/Job_Ad_QA_data/validate_set.txt'
LLM_pretrained_path: 'C:/Sample Data/Job_Ad_QA_data/saved_models/llm_saved_models'
model_output_path: 'C:/Users/Vikram Pande/Side_Projects_(OUTSIDE_REPO)/Model_Output'
training_log_path: 'C:/Users/Vikram Pande/Side_Projects_(OUTSIDE_REPO)/Training_Logs'
pretrained_HG_model: 'gpt2'
seed: 314
learning_rate: 1e-04
batch_size: 100
num_epochs: 20