model_ver: 0.01
seed: 314
content_path: 'C:/Sample Data/Ecommerce_Churn_Data/ECommerce_Dataset.xlsx'
data_path: 'C:/Sample Data/Ecommerce_Churn_Data'
utils_path: 'C:/Users/Vikram Pande/Side_Projects_(OUTSIDE_REPO)/ECommerce_Churn_Propensity_Model/src'