model_ver: 0.01
seed: 314
data_path: 'C:/Sample Data/Ecommerce_Churn_Data'
churn_app_models: 'C:/Sample Data/Ecommerce_Churn_Data/churn_app/models'
utils_path: 'C:/Users/Vikram Pande/Side_Projects_(OUTSIDE_REPO)/ECommerce_Churn_Propensity_Model/src'