model_ver: 'v0.0.1'
embedding_dim: 20
batch_size: 1024 # Use base 2 numbers to modify batch sizes (i.e. 32, 64, 128, 256, 512, etc.)
num_epochs: 20
step_size: 2
gamma: 0.1
total_loss: 0.0
files_path: 'C:/Sample Data/Recommender_data'
preprocess_path: 'C:/Users/Vikram Pande/LLM_Side_Projects/Recommender_Model/src/Preprocessing_EDA'
NCF_path: 'C:\Users\Vikram Pande\Side_Projects\Recommender_Model\src' # Path must be back slashes since the sys.path.append() call is being used