model_ver: 'v0.0.1'
embedding_dim: 20
batch_size: 32
num_epochs: 20
files_path: 'C:/Sample Data/Recommender_data'
preprocess_path: 'C:/Users/Vikram Pande/LLM_Side_Projects/Recommender_Model/src/Preprocessing_EDA'